algoritmo "semnome"
// Função :
// Autor :
// Data : 02/01/2021
// Seção de Declarações
var
n : inteiro
inicio
// Seção de Comandos
escreval("(^_^) Vamos descobrir se o numero é par ou impar?")
escreval( "digite um numero qualquer(._.):")
leia(n)
escreval(" Deixe eu pensar (`_´)....")
se (n % 2 = 0) entao
   escreval( "o numero", n," é um numero par")
senao
   escreval("o numero", n, " é um  numero impar")
fimse
fimalgoritmo
