algoritmo "semnome"
// Função :
// Autor :
// Data : 05/01/2021
// Seção de Declarações 
var
N, S:real
R :caracter
inicio
repita
      ESCREVAL("---------------------------------------")
      escreva("      digite um numero para somar: ")
      leia(N)
      ESCREVAL("---------------------------------------")
      S <- S + N
      escreva("Deseja continuar [S/N]?")
      leia(R)
      ESCREVAL("---------------------------------------")
ate ( R = "N")
ESCREVAL("---------------------------------------")
escreval("A SOMA TOTAL É DE", S,". MUITO OBRIGADO")
ESCREVAL("---------------------------------------")

fimalgoritmo
